<TransactionItem>:
    text: root.label
    divider: None
    on_release: root.on_pressed()
    _txt_top_pad: dp(4)
    _txt_bot_pad: dp(4)

    CustomIconLeftWidget:
        icon: 'account'
        padding: (0, 0, 0, 0)
        pos_hint: {'center_y': 0.5}
        # md_bg_color: get_user_color(root.key_id, alpha=0.7)
        theme_text_color: "Custom"
        text_color: app.color_white
        on_release: root.on_pressed()


<WalletScreen>:

    ScreenContainerLayout:

        TopEmptyScreenSpace:

        AppScreenLayout:

            AutomatShortStatusPanel:
                id: state_panel
                size_hint_x: 1
                statuses: root.get_statuses()

            PageContainerWithPaddingLayout:

                HorizontalMinimumHeightLayout:
                    pos_hint: {'top': 1, 'left': 0}

	                MarkupLabel:
	                    id: wallet_details
	                    size_hint_y: None
	                    text_size: self.width, None
	                    height: self.texture_size[1]
	                    color: app.color_black
	                    text: ""
	                    on_ref_press: root.on_wallet_details_ref_pressed(*args)

			    VerticalScrollView:
			        id: transactions_scroll_view

			        MDList:
			            id: transactions_list_view
			            pos_hint: {'top': 1}

        BottomEmptyScreenSpace:
