<WelcomeScreen>:

    ScreenContainerLayout:

        TopEmptyScreenSpace:

        AppScreenLayout:

            AutomatShortStatusPanel:
                id: state_panel
                size_hint_x: 1
                statuses: root.get_statuses()

		    AnchorLayout:

	            VLayout:
	                id: central_widget
	                size_hint: None, None
	                width: self.minimum_width
	                height: self.minimum_height
	                spacing: dp(20)

        BottomEmptyScreenSpace:
